variables:
  E50_SRC_2: "https://dl.ui.com/firmwares/edgemax/v2.0.8-hotfix.1/gpl/GPL.ER-e50.v2.0.8-hotfix.1.5278088.tar.bz2"
  E100_SRC: "HELLO WORLD"
  E200_SRC: "HELLO WORLD"
  E300_SRC: "HELLO WORLD"
  E1000_SRC: "HELLO WORLD"

stages:
  - docker
  - headers
  - module

docker:mipsel:
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:mipsel" -f DOCKERFILE-mipsel .
    - docker push "$CI_REGISTRY_IMAGE:mipsel"
  only:
    - master

docker:mtk:
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:mtk" -f DOCKERFILE-mtk .
    - docker push "$CI_REGISTRY_IMAGE:mtk"
  only:
    - master

docker:octeon:
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:octeon" -f DOCKERFILE-octeon .
    - docker push "$CI_REGISTRY_IMAGE:octeon"
  only:
    - master

headers:e50:
  image: $CI_REGISTRY_IMAGE:mipsel
  stage: headers
  script:
    - apt-get -y update
    - apt-get -y install bc bison flex git
    - mkdir /build $CI_PROJECT_DIR/headers
    - cd /build
    - curl -o src.tar.bz2 $URL
    - tar -xf src.tar.bz2 --wildcards 'source/kernel_*' --strip-components 1
    - mv kernel_* kernel.tar.gz
    - tar -xf kernel.tar.gz
    - make ARCH=mips ubnt_er_e50_defconfig
    - make ARCH=mips O=$CI_PROJECT_DIR/headers ubnt_er_e50_defconfig
    - make -j5 ARCH=mips CROSS_COMPILE=mipsel-linux-gnu- prepare modules_prepare
    - make -j5 ARCH=mips O=$CI_PROJECT_DIR/headers CROSS_COMPILE=mipsel-linux-gnu- modules_prepare
    - rm -rf tmp && mkdir tmp
    - make -j5 ARCH=mips CROSS_COMPILE=mipsel-linux-gnu- vmlinux modules
    - cp Module.symvers $CI_PROJECT_DIR/headers
  dependencies:
    - docker:mipsel
  artifacts:
    paths:
      - headers/
