version: 2
jobs:
  build:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run: su-exec root apt-get update
      - run: su-exec root apt-get -y install bc bison flex git
      - run: git clone -b v2.0.8/master https://github.com/Lochnair/kernel_e200.git .
      - run: make ARCH=mips ubnt_er_e200_defconfig
      - run: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- prepare modules_prepare
      - run: rm -rf tmp && mkdir tmp
      - run: tar --exclude-vcs --exclude=tmp -cf tmp/e200-ksrc.tar .
      - run: mv tmp/e200-ksrc.tar e200-ksrc.tar
      - run: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- vmlinux modules
      - run: mv -v vmlinux vmlinux.64
      - run: tar cvjf e200-kernel.tar.bz2 vmlinux.64
      - run: make ARCH=mips CROSS_COMPILE=mips64-octeon-linux- INSTALL_MOD_PATH=destdir modules_install
      - run: tar cvjf e200-modules.tar.bz2 -C destdir .
      - run: tar -uvf e200-ksrc.tar Module.symvers
      - run: bzip2 e200-ksrc.tar
      - store_test_results:
          path: /build/e200-ksrc.tar.bz2
