version: 2
jobs:
  build:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: su-exec root apt-get update
          working_directory: /build/kernel_e200
      - run:
          command: su-exec root apt-get -y install bc bison flex git
          working_directory: /build/kernel_e200
      - run:
          command: git clone -b v2.0.8/master https://github.com/Lochnair/kernel_e200.git .
          working_directory: /build/kernel_e200
      - run:
          command: make ARCH=mips ubnt_er_e200_defconfig
          working_directory: /build/kernel_e200
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- prepare modules_prepare
          working_directory: /build/kernel_e200
      - run:
          command: rm -rf tmp && mkdir tmp
          working_directory: /build/kernel_e200
      - run:
          command: tar --exclude-vcs --exclude=tmp -cf tmp/e200-ksrc.tar .
          working_directory: /build/kernel_e200
      - run:
          command: mv tmp/e200-ksrc.tar e200-ksrc.tar
          working_directory: /build/kernel_e200
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- vmlinux modules
          working_directory: /build/kernel_e200
      - run:
          command: mv -v vmlinux vmlinux.64
          working_directory: /build/kernel_e200
      - run:
          command: tar cvjf e200-kernel.tar.bz2 vmlinux.64
          working_directory: /build/kernel_e200
      - run:
          command: make ARCH=mips CROSS_COMPILE=mips64-octeon-linux- INSTALL_MOD_PATH=destdir modules_install
          working_directory: /build/kernel_e200
      - run:
          command: tar cvjf e200-modules.tar.bz2 -C destdir .
          working_directory: /build/kernel_e200
      - run:
          command: tar -uvf e200-ksrc.tar Module.symvers
          working_directory: /build/kernel_e200
      - run:
          command: bzip2 e200-ksrc.tar
          working_directory: /build/kernel_e200
      - store_artifacts:
          path: /build/e200-ksrc.tar
      - run:
          command: git clone -b v0.0.20200215 git://git.zx2c4.com/wireguard-linux-compat
          working_directory: /build/module_e200
      - run:
          command: curl -L https://gist.githubusercontent.com/Lochnair/805bf9ab96742d0fe1c25e4130268307/raw/29e37d43a5247a3f2584ef0d6d553ee9a4532e12/only-use-__vmalloc-for-now.patch | patch -p1
          working_directory: /build/module_e200
      - run:
          command: sed -i s/ --dirty//g src/Makefile
          working_directory: /build/module_e200
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- KERNELDIR=/build/kernel_e200 module
          working_directory: /build/module_e200/src
      - run:
          command: mips64-octeon-linux-strip --strip-debug wireguard.ko
          working_directory: /build/module_e200/src
      - store_artifacts:
          path: /build/module_e200/src/wireguard.ko
