version: 2
jobs:
  kernel_e100:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: su-exec root apt-get update
          working_directory: /build/kernel_e100
      - run:
          command: su-exec root apt-get -y install bc bison flex git
          working_directory: /build/kernel_e100
      - run:
          command: git clone -b v2.0.8/master https://github.com/Lochnair/kernel_e100.git .
          working_directory: /build/kernel_e100
      - run:
          command: make ARCH=mips ubnt_er_e100_defconfig
          working_directory: /build/kernel_e100
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- prepare modules_prepare
          working_directory: /build/kernel_e100
      - run:
          command: rm -rf tmp && mkdir tmp
          working_directory: /build/kernel_e100
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- vmlinux modules
          working_directory: /build/kernel_e100
      - run:
          command: make ARCH=mips CROSS_COMPILE=mips64-octeon-linux- INSTALL_MOD_PATH=destdir modules_install
          working_directory: /build/kernel_e100
      - persist_to_workspace:
          root: /build
          paths:
            - kernel_e100
  kernel_e200:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: su-exec root apt-get update
          working_directory: /build/kernel_e200
      - run:
          command: su-exec root apt-get -y install bc bison flex git
          working_directory: /build/kernel_e200
      - run:
          command: git clone -b v2.0.8/master https://github.com/Lochnair/kernel_e200.git .
          working_directory: /build/kernel_e200
      - run:
          command: make ARCH=mips ubnt_er_e200_defconfig
          working_directory: /build/kernel_e200
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- prepare modules_prepare
          working_directory: /build/kernel_e200
      - run:
          command: rm -rf tmp && mkdir tmp
          working_directory: /build/kernel_e200
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- vmlinux modules
          working_directory: /build/kernel_e200
      - run:
          command: make ARCH=mips CROSS_COMPILE=mips64-octeon-linux- INSTALL_MOD_PATH=destdir modules_install
          working_directory: /build/kernel_e200
      - persist_to_workspace:
          root: /build
          paths:
            - kernel_e200
  kernel_e300:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: su-exec root apt-get update
          working_directory: /build/kernel_e300
      - run:
          command: su-exec root apt-get -y install bc bison flex git
          working_directory: /build/kernel_e300
      - run:
          command: git clone -b v2.0.8/master https://github.com/Lochnair/kernel_e300.git .
          working_directory: /build/kernel_e300
      - run:
          command: make ARCH=mips ubnt_er_e300_defconfig
          working_directory: /build/kernel_e300
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- prepare modules_prepare
          working_directory: /build/kernel_e300
      - run:
          command: rm -rf tmp && mkdir tmp
          working_directory: /build/kernel_e300
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- vmlinux modules
          working_directory: /build/kernel_e300
      - run:
          command: make ARCH=mips CROSS_COMPILE=mips64-octeon-linux- INSTALL_MOD_PATH=destdir modules_install
          working_directory: /build/kernel_e300
      - persist_to_workspace:
          root: /build
          paths:
            - kernel_e300
  kernel_e1000:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: su-exec root apt-get update
          working_directory: /build/kernel_e1000
      - run:
          command: su-exec root apt-get -y install bc bison flex git
          working_directory: /build/kernel_e1000
      - run:
          command: git clone -b v2.0.8/master https://github.com/Lochnair/kernel_e1000.git .
          working_directory: /build/kernel_e1000
      - run:
          command: make ARCH=mips ubnt_er_e1000_defconfig
          working_directory: /build/kernel_e1000
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- prepare modules_prepare
          working_directory: /build/kernel_e1000
      - run:
          command: rm -rf tmp && mkdir tmp
          working_directory: /build/kernel_e1000
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- vmlinux modules
          working_directory: /build/kernel_e1000
      - run:
          command: make ARCH=mips CROSS_COMPILE=mips64-octeon-linux- INSTALL_MOD_PATH=destdir modules_install
          working_directory: /build/kernel_e1000
      - persist_to_workspace:
          root: /build
          paths:
            - kernel_e1000
  clone_module:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - run:
          command: git clone -b v0.0.20200215 git://git.zx2c4.com/wireguard-linux-compat .
          working_directory: /build/module
      - run:
          command: curl -L https://gist.githubusercontent.com/Lochnair/805bf9ab96742d0fe1c25e4130268307/raw/29e37d43a5247a3f2584ef0d6d553ee9a4532e12/only-use-__vmalloc-for-now.patch | patch compat.h
          working_directory: /build/module/src/compat
      - run:
          command: sed -i 's/ --dirty//g' src/Makefile
          working_directory: /build/module
      - persist_to_workspace:
          root: /build
          paths:
            - module
  module_e100:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - attach_workspace:
          at: /build
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- KERNELDIR=/build/kernel_e100 module
          working_directory: /build/module/src
      - run:
          command: mips64-octeon-linux-strip --strip-debug wireguard.ko
          working_directory: /build/module/src
      - run:
          command: mv wireguard.ko wireguard_e100.ko
          working_directory: /build/module/src
      - persist_to_workspace:
          root: /build
          paths:
            - module/src/wireguard_e100.ko
  module_e200:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - attach_workspace:
          at: /build
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- KERNELDIR=/build/kernel_e200 module
          working_directory: /build/module/src
      - run:
          command: mips64-octeon-linux-strip --strip-debug wireguard.ko
          working_directory: /build/module/src
      - run:
          command: mv wireguard.ko wireguard_e200.ko
          working_directory: /build/module/src
      - persist_to_workspace:
          root: /build
          paths:
            - module/src/wireguard_e200.ko
  module_e300:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - attach_workspace:
          at: /build
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- KERNELDIR=/build/kernel_e300 module
          working_directory: /build/module/src
      - run:
          command: mips64-octeon-linux-strip --strip-debug wireguard.ko
          working_directory: /build/module/src
      - run:
          command: mv wireguard.ko wireguard_e300.ko
          working_directory: /build/module/src
      - persist_to_workspace:
          root: /build
          paths:
            - module/src/wireguard_e300.ko
  module_e1000:
    docker:
      - image: lochnair/octeon-buildenv:latest
    working_directory: /build/
    steps:
      - attach_workspace:
          at: /build
      - run:
          command: make -j5 ARCH=mips CROSS_COMPILE=mips64-octeon-linux- KERNELDIR=/build/kernel_e1000 module
          working_directory: /build/module/src
      - run:
          command: mips64-octeon-linux-strip --strip-debug wireguard.ko
          working_directory: /build/module/src
      - run:
          command: mv wireguard.ko wireguard_e1000.ko
          working_directory: /build/module/src
      - persist_to_workspace:
          root: /build
          paths:
            - module/src/wireguard_e1000.ko
  tools_mips:
    docker:
      - image: lochnair/musl-buildenv:mips
    working_directory: /build/
    steps:
      - run:
          command: git clone -b v1.0.20200206 git://git.zx2c4.com/wireguard-tools .
          working_directory: /build/tools-mips
      - run:
          command: CC="mips-linux-musl-gcc" LDLIBS="-static" make -j5
          working_directory: /build/tools-mips/src
      - run:
          command: mips-linux-musl-strip --strip-unneeded wg
          working_directory: /build/tools-mips/src
      - run:
          command: CC="mips-linux-musl-gcc" LDLIBS="-static" make -j5
          working_directory: /build/tools-mips/src
      - persist_to_workspace:
          root: /build
          paths:
            - tools-mips/src/wg
  tools_mipsel:
    docker:
      - image: lochnair/musl-buildenv:mipsel
    working_directory: /build/
    steps:
      - run:
          command: git clone -b v1.0.20200206 git://git.zx2c4.com/wireguard-tools .
          working_directory: /build/tools-mipsel
      - run:
          command: CC="mips-linux-musl-gcc" LDLIBS="-static" make -j5
          working_directory: /build/tools-mipsel/src
      - run:
          command: mips-linux-musl-strip --strip-unneeded wg
          working_directory: /build/tools-mipsel/src
      - run:
          command: CC="mips-linux-musl-gcc" LDLIBS="-static" make -j5
          working_directory: /build/tools-mipsel/src
      - persist_to_workspace:
          root: /build
          paths:
            - tools-mipsel/src/wg
  package:
    docker:
      - image: debian
    working_directory: /build/
    steps:
      - attach_workspace:
          at: /build
      - store_artifacts:
          path: /build/module/src/wireguard_e100.ko
          destination: wireguard_e100.ko
      - store_artifacts:
          path: /build/module/src/wireguard_e200.ko
          destination: wireguard_e200.ko
      - store_artifacts:
          path: /build/module/src/wireguard_e300.ko
          destination: wireguard_e300.ko
      - store_artifacts:
          path: /build/module/src/wireguard_e1000.ko
          destination: wireguard_e1000.ko
      - store_artifacts:
          path: /build/tools-mips/src/wg
          destination: wg-mips
      - store_artifacts:
          path: /build/tools-mipsel/src/wg
          destination: wg-mipsel

workflows:
  version: 2

  build_modules:
    jobs:
      - kernel_e100
      - kernel_e200
      - kernel_e300
      - kernel_e1000
      - clone_module
      - module_e100:
          requires:
            - clone_module
            - kernel_e100
      - module_e200:
          requires:
            - clone_module
            - kernel_e200
      - module_e300:
          requires:
            - clone_module
            - kernel_e300
      - module_e1000:
          requires:
            - clone_module
            - kernel_e1000
      - tools_mips
      - tools_mipsel
      - package:
          requires:
            - module_e100
            - module_e200
            - module_e300
            - module_e1000
            - tools_mips
            - tools_mipsel
